# -*- coding: utf-8 -*-
"""Analisis_Clustering_Performa_Siswa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwl6GXyNxz860q5wS6qeaDYqU066zFFm
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Load the dataset with the correct delimiter
df = pd.read_csv('/content/student-mat.csv', delimiter=';')

# 1. Pilih hanya kolom numerik yang relevan untuk clustering
# Kita fokus pada waktu belajar, kegagalan, absensi, dan nilai ujian
features = ['studytime', 'failures', 'absences', 'G1', 'G2', 'G3']
X = df[features]

# 2. Standarisasi data (PENTING agar skala fitur seperti G3 dan absences tidak timpang)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3. Metode Elbow untuk mencari jumlah cluster (K) terbaik
inertia = []
K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

# Plot grafik Elbow
plt.figure(figsize=(8, 4))
plt.plot(K_range, inertia, marker='o')
plt.title('Grafik Elbow untuk Menentukan Jumlah Cluster')
plt.xlabel('Jumlah Cluster (K)')
plt.ylabel('Inertia')
plt.show()

# 4. Setelah melihat grafik elbow (biasanya di angka 3 atau 4), jalankan K-Means
# Misal kita pilih K=3
k_final = 3
kmeans_final = KMeans(n_clusters=k_final, random_state=42)
df['Cluster'] = kmeans_final.fit_predict(X_scaled)

# 5. Tampilkan hasil pengelompokan
print("Hasil rata-rata nilai per cluster:")
print(df.groupby('Cluster')[features].mean())

# Membuat tabel hasil yang lebih rapi
hasil_cluster = df.groupby('Cluster')[features].mean()

# Menampilkan tabel
print("\n--- Tabel Karakteristik Per Cluster ---")
display(hasil_cluster)

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# 1. Load Data
df = pd.read_csv('/student-mat-csv.csv', sep=';')

# 2. Preprocessing & Seleksi Fitur
features = ['studytime', 'failures', 'absences', 'G1', 'G2', 'G3']
X = df[features]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3. K-Means dengan K=3 (Kelompok umum: Berprestasi, Menengah, Berisiko)
kmeans = KMeans(n_clusters=3, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

# 4. Menampilkan Ringkasan
print("--- Ringkasan Analisis Per Cluster ---")
print(df.groupby('Cluster')[features].mean())

# 5. Visualisasi Hasil
plt.figure(figsize=(10, 6))
scatter = plt.scatter(df['G3'], df['absences'], c=df['Cluster'], cmap='viridis', s=50, alpha=0.6)
plt.title('Visualisasi Pengelompokan Siswa (K-Means)')
plt.xlabel('Nilai Akhir (G3)')
plt.ylabel('Jumlah Absensi')
plt.colorbar(scatter, label='Cluster')
plt.show()